### ISSUE TITLE
Fix README to use a Ragtag contact email

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/localhost#11]
Also might need to update some of the instructions?

**Comment by bradyk** [comment]
I have updated the readme to replace sam's email address with an info@ragtag.org one.

I replaced a mention or two of people's housing and marchbnb.

I did NOT replace any of the mentions of marchbnb in the instructions. Someone else should do that.

Created a new issue so I can close this one. https://github.com/RagtagOpen/localhost/issues/20
