### ISSUE TITLE
Use SwingLeft's privacy policy and TOS

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/localhost#12]
Replace current privacy policy and TOS links with these:

https://swingleft.org/privacy
https://swingleft.org/term-of-use

**Comment by bradyk** [comment]
Made this new Privacy Policy. https://github.com/RagtagOpen/localhost/blob/master/app/views/pages/privacy_policy.html.erb 

Still needs to be linked to from the applicable places.

**Comment by bradyk** [comment]
I have updated the existing Terms page to have SL's language - https://github.com/RagtagOpen/localhost/blob/master/app/views/pages/terms_of_service.html.erb

**Comment by bradyk** [comment]
fixed in staging
