### ISSUE TITLE
Add disclaimer to RSVP

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/localhost#13]
Pls add to the UI:

By clicking RSVP, you agree to Swing Left’s Organizer Liability Statement. (link to https://swingleft.org/p/liability)

**Comment by bradyk** [comment]
https://github.com/RagtagOpen/localhost/blob/staging/app/views/users/edit.html.haml

Please update the part that says "I accept the Terms of Service" to 

I accept the Terms of Use and the Swing Left Organizer Liability Statement

With Terms of Use linking to /terms_of_service and Swing Left Organizer Liability Statement linking to https://swingleft.org/p/liability
