### ISSUE TITLE
Simplify Docker setup

### ISSUE THREAD

**Issue by jkriss** [RagtagOpen/localhost#29]
We should be able to avoid the multi-step Docker instructions in the Readme and just use Docker Compose.

There is a `docker-compose.yml` file already, but the usual `docker-compose up` doesn't seem to do the trick.

We should figure out how to get this working properly, then update the Readme.

**Comment by samuelcole** [comment]
fwiw: i inherited docker, and some people found it hard to set up local envs in linux/windows, so we decided to get rid of it...

i'm not against it? just whatever is actually usable for contributors...

**Comment by jkriss** [comment]
Hm, good to know. There was still a lot of space devoted to it in the Readme, and with these changes, the setup should be significantly easier.

I didn’t change anything that effected the non-Docker setup, so this should theoretically be a positive change without any negative side effects.

I won’t speak for orhers, but for me, having a quick Docker set up makes is far easier to contribute.

**Comment by samuelcole** [comment]
yup, most people just skip all that, and run rails uncontained ;-)

i believe heroku is configured to use the normal rails buildpack these days
