### ISSUE TITLE
Make SwingLeft logo smaller

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/localhost#3]

**Comment by jillh510** [comment]
Official versions of the Swing Left logos are at https://www.lingoapp.com/space/70062/k/CE6C7E49-A1AE-4501-9038-3B9CD1F01EB5/11D8F700-381A-4019-85B6-5BC5BB1142FF/?tkn=5bgDa7NR-4oKIPrQwXVF3to983sr4E_VBmf8h5FqlA0

**Comment by jillh510** [comment]
Also please check it on mobile.

**Comment by bradyk** [comment]
![swing left localhost logo](https://user-images.githubusercontent.com/1565834/36503837-5710e0ae-1703-11e8-9e08-3c004fb3e833.png)
Please use this logo! Thanks!
