### ISSUE TITLE
Update preview/unfurl text

### ISSUE THREAD

**Issue by iandees** [RagtagOpen/localhost#6]
![image](https://user-images.githubusercontent.com/261584/35935019-cbded850-0c04-11e8-92f2-761f88ac550b.png)

There's an extra apostrophe at the beginning of the preview/unfurl text.

**Comment by samuelcole** [comment]
and it still says 'people's housing'

**Comment by samuelcole** [comment]
https://github.com/RagtagOpen/localhost/blob/master/app/views/layouts/application.html.erb#L10
