### ISSUE TITLE
Check colors in Localhost against official Swing Left branding

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/localhost#8]
Swing Left's official branding is found here: https://www.lingoapp.com/space/70062/k/CE6C7E49-A1AE-4501-9038-3B9CD1F01EB5/11D8F700-381A-4019-85B6-5BC5BB1142FF/?tkn=5bgDa7NR-4oKIPrQwXVF3to983sr4E_VBmf8h5FqlA0

This issue stands for checking the colors on localhost.ragtag.org against the colors in the official guide, fixing as needed.

**Comment by bradyk** [comment]
@jillh510 I just made a (somewhat duplicate) issue to track a couple of things I saw that needed changing wrt branding.
https://github.com/RagtagOpen/localhost/issues/18
